/**
 * Búsqueda de productos
 */

// Del usuario para buscar un producto
export const search_product = [
  'Quiero un *',
  'Quiero una *',
  'Quiero buscar un *',
  'Quiero buscar una *',
  'Quiero que busques un *',
  'Quiero que busques una *',
  'Búscame un *',
  'Búscame una *',
  'Encuentra un *',
  'Encuentra una *',
  'Quiero comprar un *',
  'Quiero comprar una *',
  'Podrías buscar un *',
  'Podrías buscar una *',
  'Buscar *',
  'Busca un *',
  'Busca una *',
  'Busca la *',
  'Busca el *',
  'Deseo una *',
  'Deseo un *',
  'Deseo buscar un *',
  'Deseo buscar una *',
  'Deseo que busques un *',
  'Deseo que busques una *',
  'Por favor quiero un *',
  'Por favor quiero una *',
  'Por favor quiero buscar un *',
  'Por favor quiero buscar una *',
  'Por favor quiero que busques un *',
  'Por favor quiero que busques una *',
  'Por favor búscame un *',
  'Por favor búscame una *',
  'Por favor encuentra un *',
  'Por favor encuentra una *',
  'Por favor quiero comprar un *',
  'Por favor quiero comprar una *',
  'Por favor podrías buscar un *',
  'Por favor podrías buscar una *',
  'Por favor busca un *',
  'Por favor busca una *',
  'Por favor busca la *',
  'Por favor busca el *',
  'Por favor deseo una *',
  'Por favor deseo un *',
  'Por favor deseo buscar un *',
  'Por favor deseo buscar una *',
  'Por favor deseo que busques un *',
  'Por favor deseo que busques una *',
]
// Luego de buscar el producto te mostrará una interfaz con todas las coincidencias y con el seleccionador en el primer producto, osea el de la izquierda superior.

export const search_by_category_selected = [
  // Minúsculas
  'categoría *',
  'categoría *.',
  'ir a categoría *',
  'ir a categoría *.',
  'ir a la categoría *',
  'ir a la categoría *.',
  'buscar por categoría número *',
  'buscar por categoría número *.',
  'buscar categoría número *',
  'buscar categoría número *.',
  'buscar categoría *',
  'buscar categoría *.',
  'buscar productos por categoría número *',
  'buscar productos por categoría número *.',
  'buscar productos categoría número *',
  'buscar productos categoría número *.',
  'buscar productos categoría *',
  'buscar productos categoría *.',
  'buscar productos relacionados con categoría número *',
  'buscar productos relacionados con categoría número *.',
  'buscar productos relacionados con categoría *',
  'buscar productos relacionados con categoría *.',
  'buscar, por categoría número *',
  'buscar, por categoría número *.',
  'buscar, categoría número *',
  'buscar, categoría número *.',
  'buscar, categoría *',
  'buscar, categoría *.',
  'buscar, productos por categoría número *',
  'buscar, productos por categoría número *.',
  'buscar, productos categoría número *',
  'buscar, productos categoría número *.',
  'buscar, productos categoría *',
  'buscar, productos categoría *.',
  'buscar, productos relacionados con categoría número *',
  'buscar, productos relacionados con categoría número *.',
  'buscar, productos relacionados con categoría *',
  'buscar, productos relacionados con categoría *.',
  'llévame a la categoría *',
  'llévame a la categoría *.',
  'llévame a la categoría número *',
  'llévame a la categoría número *.',
  'entra a la categoría *',
  'entra a la categoría *.',
  'entra a la categoría número *',
  'entra a la categoría número *.',
  'entrar a la categoría *',
  'entrar a la categoría *.',
  'entrar a la categoría número *',
  'entrar a la categoría número *.',

  // Mayúsculas sin punto
  'Categoría *',
  'Ir a categoría *',
  'Ir a la categoría *',
  'Buscar por categoría número *',
  'Buscar categoría número *',
  'Buscar categoría *',
  'Buscar productos por categoría número *',
  'Buscar productos categoría número *',
  'Buscar productos categoría *',
  'Buscar productos relacionados con categoría número *',
  'Buscar productos relacionados con categoría *',
  'Buscar, por categoría número *',
  'Buscar, categoría número *',
  'Buscar, categoría *',
  'Buscar, productos por categoría número *',
  'Buscar, productos categoría número *',
  'Buscar, productos categoría *',
  'Buscar, productos relacionados con categoría número *',
  'Buscar, productos relacionados con categoría *',
  'Llévame a la categoría *',
  'Llévame a la categoría número *',
  'Entra a la categoría *',
  'Entra a la categoría número *',
  'Entrar a la categoría *',
  'Entrar a la categoría número *',

  // Mayúsculas con punto
  'Categoría *.',
  'Ir a categoría *.',
  'Ir a la categoría *.',
  'Buscar por categoría número *.',
  'Buscar categoría número *.',
  'Buscar categoría *.',
  'Buscar productos por categoría número *.',
  'Buscar productos categoría número *.',
  'Buscar productos categoría *.',
  'Buscar productos relacionados con categoría número *.',
  'Buscar productos relacionados con categoría *.',
  'Buscar, por categoría número *.',
  'Buscar, categoría número *.',
  'Buscar, categoría *.',
  'Buscar, productos por categoría número *.',
  'Buscar, productos categoría número *.',
  'Buscar, productos categoría *.',
  'Buscar, productos relacionados con categoría número *.',
  'Buscar, productos relacionados con categoría *.',
  'Llévame a la categoría *.',
  'Llévame a la categoría número *.',
  'Entra a la categoría *.',
  'Entra a la categoría número *.',
  'Entrar a la categoría *.',
  'Entrar a la categoría número *.',
]
